#!/bin/bash

volon=$(amixer get Master | awk '$0~/%/{print $6}' | tr -d '[]%')
if [ $volon == "off" ]; then
  vol="OFF"
  echo "$vol"
else
  vol="$(amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]%')"
  echo "$vol%"
fi
